# Generated by Django 5.2.4 on 2025-08-16 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_remove_submissions_runtime_submissions_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissions',
            name='runtime',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submissions',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='submissions',
            name='total_score',
            field=models.IntegerField(default=0),
        ),
    ]
