# Generated by Django 5.2.5 on 2025-08-17 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('time_limit_ms', models.PositiveIntegerField(default=1000)),
                ('memory_limit_mb', models.PositiveIntegerField(default=256)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('cpp17', 'C++17'), ('c', 'C11'), ('py3', 'Python 3'), ('java', 'Java 17')], max_length=10)),
                ('source', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verdict', models.CharField(default='Queued', max_length=30)),
                ('time_ms', models.IntegerField(default=0)),
                ('memory_kb', models.IntegerField(default=0)),
                ('message', models.TextField(blank=True, default='')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subs', to='judge.problem')),
            ],
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.TextField(blank=True, default='')),
                ('output_data', models.TextField()),
                ('is_sample', models.BooleanField(default=False)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='judge.problem')),
            ],
        ),
    ]
