# Generated by Django 5.2.4 on 2025-08-13 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_problem_description_problem_input_format_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='expected_output',
            field=models.TextField(blank=True, help_text='Expected output for the given input'),
        ),
        migrations.AddField(
            model_name='problem',
            name='input_data',
            field=models.TextField(blank=True, help_text="sample input to be given to the user's code"),
        ),
    ]
